### ISSUE TITLE
issues with new patching method

### ISSUE THREAD

**Issue by rickardjanson** [crysalead-js/dom-layer#38]
Hi.  I'm back to normal, and the electricity is back too. So time for finding your bugs again :)

Your new `patch` has some problems it seems for me at least. Test cases and everything working just fine, but have you tried your `input example`?

Try it, and see if you encounter the same issues as me. Here is my findings:

- Textarea working just fine
- checkbox loose state, Can only be clicked once
- 3 radio buttons, but only 2 of them you can click on. The one in the middle are dead

**Comment by rickardjanson** [comment]
- In the multiselect - **Select Multiple:**. Mark A, B C - all 3. Hold down CTRL-key ( windows PC) and click on the **B**.  You see now what happen?  That is dead too.

**Comment by rickardjanson** [comment]
After checking, I think this is related to the text nodes.

**Comment by jails** [comment]
I think the issue has been fixed in https://github.com/crysalead-js/dom-layer/commit/3af9921658fd8c706759b9d4bfe030bf3dc096e3

**Comment by rickardjanson** [comment]
Issue seems to be fixed, but I still experience a little slow-down in FF. I don't have any Android phone by hand, but one of my colleagues tested on Android with stock browser, and told me about some lags. Android 4.3.

**Comment by jails** [comment]
Weird, just tested on my Android 4.1.2 and locally with Firefox & Chrome (linux) for both the speedtest and the input example and I didn't noticed any lag or slow-down issue.

**Comment by rickardjanson** [comment]
In many cases,code can act different from device to device. However, me too did a re-search on this to try to help you out. And I didn't find a good solution, except it looks like you don't need the `slice()` in the patch function. At least the code run very well without it and didn't have any FF issues now.

After more re-search, I found this gist: https://gist.github.com/brettz9/6093105

Maybe this could be used to speed things up etc?

**Comment by jails** [comment]
I updated the patching strategy to use the [snabbdom
](https://github.com/paldepind/snabbdom) implementation https://github.com/paldepind/snabbdom/blob/master/snabbdom.js#L117-171 which reach similar performances as the citojs one. So it shouldn't create further slow-down than the former implementation.
And I used `splice()` because the patching algorithm is destructive at some point https://github.com/crysalead-js/dom-layer/blob/master/tree/patch.js#L63 and even if it should work w/o it, I think it's better to not mutate a passed parameter (even if the chilren array shouldn't be used any more). However you shouln't notice any performance impact.
On my Android 4.1.2 I reach on the speedtest beachmark:
≈250 ms for the dom-layer
≈200 ms for cito
>= 2000 ms for React

Soe we are in good shape imo.

**Comment by rickardjanson** [comment]
I get it. And I guess in the future you will know if any others encounter problems through issue tickets.
But great performance! Challenge now would be to beat citojs? Using range(), insertAsjacentHTML etc ?

**Comment by jails** [comment]
Not really, just wanted to make a flexible customizable virtual dom implementation to start a front end library on top of it (similar to the deku one). I think the performances with the new strategy are decent enough http://vdom-benchmark.github.io/vdom-benchmark/ for all the features this library provide.
